#!/usr/bin/env python3
"""Generate the Rust lookup table from WHATWG's entities.json."""

import json
from pathlib import Path
from urllib.request import urlopen


destination = Path(__file__).parents[1] / "src" / "html" / "entities_table.rs"
source_url = "https://html.spec.whatwg.org/entities.json"

with urlopen(source_url) as response:
    source = json.load(response)

entries = sorted((name.removeprefix("&"), value["characters"]) for name, value in source.items())

with destination.open("w", encoding="utf-8", newline="\n") as output:
    output.write("// @generated by scripts/generate_entities.py; do not edit.\n")
    output.write(f"// Source: {source_url}\n\n")
    output.write(
        f"pub(super) const MAX_NAME_LEN: usize = {max(len(name) for name, _ in entries)};\n\n"
    )
    output.write(
        f"pub(super) static NAMED_ENTITIES: [(&str, &str); {len(entries)}] = [\n"
    )
    for name, value in entries:
        output.write(
            f"    ({json.dumps(name, ensure_ascii=True)}, "
            f"{json.dumps(value, ensure_ascii=True)}),\n"
        )
    output.write("];\n")
