#!/usr/bin/env python3
"""Generate the Rust lookup table from WHATWG's entities.json.

Usage:
  python crates/scah/scripts/generate_entities.py
  python crates/scah/scripts/generate_entities.py --input crates/scah/scripts/entities.json

By default, reads the committed fixture next to this script so regeneration is
offline and deterministic. Pass --fetch to download from the WHATWG URL instead.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import tempfile
import unicodedata
from datetime import datetime, timezone
from pathlib import Path
from urllib.request import urlopen


SCRIPT_PATH = Path(__file__).resolve()
DEFAULT_INPUT = SCRIPT_PATH.with_name("entities.json")
DESTINATION = SCRIPT_PATH.parents[1] / "src" / "html" / "entities_table.rs"
SOURCE_URL = "https://html.spec.whatwg.org/entities.json"
GENERATOR_REL = "crates/scah/scripts/generate_entities.py"


def rust_string_literal(value: str) -> str:
    """Encode a Rust double-quoted string literal without UTF-16 surrogates."""
    pieces: list[str] = ['"']

    for char in value:
        code = ord(char)
        category = unicodedata.category(char)

        if char == "\\":
            pieces.append("\\\\")
        elif char == '"':
            pieces.append('\\"')
        elif char == "\n":
            pieces.append("\\n")
        elif char == "\r":
            pieces.append("\\r")
        elif char == "\t":
            pieces.append("\\t")
        elif char == "\0":
            pieces.append("\\0")
        elif code < 0x20 or code == 0x7F or category in {"Cc", "Cf", "Zl", "Zp"}:
            pieces.append(f"\\u{{{code:X}}}")
        elif category == "Zs" and code != 0x20:
            # Keep ordinary ASCII space literal; escape other Unicode spaces.
            pieces.append(f"\\u{{{code:X}}}")
        else:
            pieces.append(char)

    pieces.append('"')
    return "".join(pieces)


def load_source(raw: bytes) -> tuple[dict, str]:
    source_hash = hashlib.sha256(raw).hexdigest()
    source = json.loads(raw.decode("utf-8"))
    if not isinstance(source, dict):
        raise SystemExit("entities source must be a JSON object")
    return source, source_hash


def generate_table(source: dict, source_hash: str, retrieved: str) -> str:
    entries = sorted(
        (name.removeprefix("&"), value["characters"]) for name, value in source.items()
    )
    lines = [
        f"// @generated by {GENERATOR_REL}; do not edit.",
        f"// Source: {SOURCE_URL}",
        f"// Source SHA-256: {source_hash}",
        f"// Entry count: {len(entries)}",
        f"// Retrieved: {retrieved}",
        "",
        f"pub(super) const MAX_NAME_LEN: usize = {max(len(name) for name, _ in entries)};",
        "",
        f"pub(super) static NAMED_ENTITIES: [(&str, &str); {len(entries)}] = [",
    ]
    for name, value in entries:
        lines.append(
            f"    ({rust_string_literal(name)}, {rust_string_literal(value)}),"
        )
    lines.append("];")
    lines.append("")
    return "\n".join(lines)


def atomic_write(destination: Path, content: str) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        newline="\n",
        dir=destination.parent,
        prefix=f".{destination.name}.",
        suffix=".tmp",
        delete=False,
    ) as handle:
        handle.write(content)
        temporary = Path(handle.name)
    temporary.replace(destination)


def self_test() -> None:
    expected = {
        "plain": '"plain"',
        'quote: "': '"quote: \\""',
        "slash: \\": '"slash: \\\\"',
        "\u0001": '"\\u{1}"',
        "\n": '"\\n"',
        "\t": '"\\t"',
        "\u2061": '"\\u{2061}"',
        "𝔄": '"𝔄"',
        "\u2242\u0338": '"\u2242\u0338"',
    }
    for value, want in expected.items():
        got = rust_string_literal(value)
        if got != want:
            raise AssertionError(f"rust_string_literal({value!r}) = {got!r}, want {want!r}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        default=DEFAULT_INPUT,
        help="Path to entities.json (default: committed fixture beside this script)",
    )
    parser.add_argument(
        "--fetch",
        action="store_true",
        help=f"Download {SOURCE_URL} instead of reading --input",
    )
    parser.add_argument(
        "--self-test",
        action="store_true",
        help="Run escaping self-tests and exit",
    )
    args = parser.parse_args(argv)

    if args.self_test:
        self_test()
        print("self-test ok")
        return 0

    if args.fetch:
        with urlopen(SOURCE_URL) as response:
            raw = response.read()
        retrieved = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    else:
        raw = args.input.read_bytes()
        retrieved = "committed-fixture"

    source, source_hash = load_source(raw)
    content = generate_table(source, source_hash, retrieved)
    atomic_write(DESTINATION, content)
    print(f"wrote {DESTINATION}")
    print(f"source sha-256: {source_hash}")
    print(f"entry count: {len(source)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
