/* scah C ABI — generated by cbindgen. Do not edit by hand. */

#ifndef SCAH_H
#define SCAH_H

#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>

// Result status for every fallible C ABI function.
typedef enum ScahStatus {
  ScahStatus_Ok = 0,
  ScahStatus_NullPointer = 1,
  ScahStatus_InvalidUtf8 = 2,
  ScahStatus_InvalidSelector = 3,
  ScahStatus_EmptyQueries = 4,
  ScahStatus_MaximumDepthExceeded = 5,
  ScahStatus_InvalidSection = 6,
  ScahStatus_IndexOutOfBounds = 7,
  ScahStatus_InternalPanic = 8,
} ScahStatus;

// Opaque element handle. Keeps its store alive.
typedef struct ScahElement ScahElement;

// Opaque list of element ids sharing a store.
typedef struct ScahElementList ScahElementList;

// Owned diagnostic message allocated by the FFI layer.
typedef struct ScahError ScahError;

// Opaque compiled query handle.
typedef struct ScahQuery ScahQuery;

// Opaque pending query builder handle.
typedef struct ScahQueryBuilder ScahQueryBuilder;

// Opaque parsed store handle.
typedef struct ScahStore ScahStore;

// A non-owning UTF-8 string view (`pointer` + `length`).
//
// Never requires a NUL terminator. A null `data` pointer is only valid when
// `len == 0`.
typedef struct ScahStringView {
  const uint8_t *data;
  size_t len;
} ScahStringView;

// Which content to capture for matched elements.
typedef struct ScahSave {
  uint8_t inner_html;
  uint8_t text_content;
} ScahSave;

// Section identifier within a query builder tree.
typedef size_t ScahQuerySectionId;

// Optional string view. Distinguish missing values from empty strings with
// `is_some` rather than overloading null pointers.
typedef struct ScahOptionalStringView {
  struct ScahStringView value;
  uint8_t is_some;
} ScahOptionalStringView;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Borrow the error message. Valid while `error` remains alive.
struct ScahStringView scah_error_message(const struct ScahError *error);

// Free an error handle. Null is a no-op.
void scah_error_free(struct ScahError *error);

// Create a root builder that matches all occurrences of `selector`.
//
// The selector is not validated until [`scah_query_builder_build`].
enum ScahStatus scah_query_all(struct ScahStringView selector,
                               struct ScahSave save,
                               struct ScahQueryBuilder **out_builder,
                               struct ScahError **out_error);

// Create a root builder that matches the first occurrence of `selector`.
enum ScahStatus scah_query_first(struct ScahStringView selector,
                                 struct ScahSave save,
                                 struct ScahQueryBuilder **out_builder,
                                 struct ScahError **out_error);

// Append a linear `all` child under the builder's current last section.
enum ScahStatus scah_query_builder_all(struct ScahQueryBuilder *builder,
                                       struct ScahStringView selector,
                                       struct ScahSave save,
                                       struct ScahError **out_error);

// Append a linear `first` child under the builder's current last section.
enum ScahStatus scah_query_builder_first(struct ScahQueryBuilder *builder,
                                         struct ScahStringView selector,
                                         struct ScahSave save,
                                         struct ScahError **out_error);

// Return the current (last) section id for subsequent [`scah_query_builder_append`] calls.
enum ScahStatus scah_query_builder_current_section(const struct ScahQueryBuilder *builder,
                                                   ScahQuerySectionId *out_section,
                                                   struct ScahError **out_error);

// Clone `child` under `parent` without consuming either builder.
enum ScahStatus scah_query_builder_append(struct ScahQueryBuilder *builder,
                                          ScahQuerySectionId parent,
                                          const struct ScahQueryBuilder *child,
                                          struct ScahError **out_error);

// Compile the builder into a query. Does not consume the builder.
enum ScahStatus scah_query_builder_build(const struct ScahQueryBuilder *builder,
                                         struct ScahQuery **out_query,
                                         struct ScahError **out_error);

// Deep-clone a builder handle.
enum ScahStatus scah_query_builder_clone(const struct ScahQueryBuilder *builder,
                                         struct ScahQueryBuilder **out_builder,
                                         struct ScahError **out_error);

// Free a builder handle. Null is a no-op.
void scah_query_builder_free(struct ScahQueryBuilder *builder);

// Free a query handle. Null is a no-op.
void scah_query_free(struct ScahQuery *query);

// Current C ABI version.
uint32_t scah_abi_version(void);

// Parse HTML against one or more compiled queries.
//
// Returned string views from the store/elements borrow store-owned HTML and
// remain valid only while those handles are alive.
enum ScahStatus scah_parse(struct ScahStringView html,
                           const struct ScahQuery *const *queries,
                           size_t query_count,
                           struct ScahStore **out_store,
                           struct ScahError **out_error);

// Number of elements in the store.
enum ScahStatus scah_store_len(const struct ScahStore *store,
                               size_t *out_len,
                               struct ScahError **out_error);

// Look up elements matched by `query`.
//
// When the selector is absent, `*out_found` is set to 0 and this is not an error.
enum ScahStatus scah_store_get(const struct ScahStore *store,
                               struct ScahStringView query,
                               struct ScahElementList **out_elements,
                               uint8_t *out_found,
                               struct ScahError **out_error);

// Free a store handle. Null is a no-op.
void scah_store_free(struct ScahStore *store);

// Length of an element list.
enum ScahStatus scah_element_list_len(const struct ScahElementList *list,
                                      size_t *out_len,
                                      struct ScahError **out_error);

// Get an element handle from a list. The element retains its own store `Arc`.
enum ScahStatus scah_element_list_get(const struct ScahElementList *list,
                                      size_t index,
                                      struct ScahElement **out_element,
                                      struct ScahError **out_error);

// Free an element list. Null is a no-op.
void scah_element_list_free(struct ScahElementList *list);

// Element tag name. Borrowed from store-owned HTML.
enum ScahStatus scah_element_name(const struct ScahElement *element,
                                  struct ScahStringView *out_name,
                                  struct ScahError **out_error);

// Element `id` attribute, if present.
enum ScahStatus scah_element_id(const struct ScahElement *element,
                                struct ScahOptionalStringView *out_id,
                                struct ScahError **out_error);

// Element `class` attribute, if present.
enum ScahStatus scah_element_class_name(const struct ScahElement *element,
                                        struct ScahOptionalStringView *out_class,
                                        struct ScahError **out_error);

// Element inner HTML, if captured.
enum ScahStatus scah_element_inner_html(const struct ScahElement *element,
                                        struct ScahOptionalStringView *out_html,
                                        struct ScahError **out_error);

// Element text content, if captured.
enum ScahStatus scah_element_text_content(const struct ScahElement *element,
                                          struct ScahOptionalStringView *out_text,
                                          struct ScahError **out_error);

// Look up a single attribute by name.
enum ScahStatus scah_element_get_attribute(const struct ScahElement *element,
                                           struct ScahStringView key,
                                           struct ScahOptionalStringView *out_value,
                                           struct ScahError **out_error);

// Number of extra attributes (excluding dedicated class/id fields).
enum ScahStatus scah_element_attribute_count(const struct ScahElement *element,
                                             size_t *out_count,
                                             struct ScahError **out_error);

// Indexed attribute access without building a hash map.
//
// When an attribute has no value, `out_value` is an empty string view.
enum ScahStatus scah_element_attribute_at(const struct ScahElement *element,
                                          size_t index,
                                          struct ScahStringView *out_key,
                                          struct ScahStringView *out_value,
                                          struct ScahError **out_error);

// Nested query lookup on an element.
//
// When the child query is absent, `*out_found` is 0 (not an error).
enum ScahStatus scah_element_get(const struct ScahElement *element,
                                 struct ScahStringView query,
                                 struct ScahElementList **out_elements,
                                 uint8_t *out_found,
                                 struct ScahError **out_error);

// Free an element handle. Null is a no-op.
void scah_element_free(struct ScahElement *element);

// Capture neither inner HTML nor text content.
struct ScahSave scah_save_none(void);

// Capture both inner HTML and text content.
struct ScahSave scah_save_all(void);

// Capture only inner HTML.
struct ScahSave scah_save_only_inner_html(void);

// Capture only text content.
struct ScahSave scah_save_only_text_content(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SCAH_H */
